"use client";

import { useState, useEffect, useRef } from 'react';
import { useStoredInput } from '@/hooks/useStoredInput';
import { callGroqApi } from '@/utils/groqApi';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import Link from 'next/link';

export default function ICPCreationContent() {
  const [userInput, setUserInput] = useStoredInput();
  const [icpAnalysis, setIcpAnalysis] = useState({
    demographics: [],
    psychographics: [],
    professional: [],
    pain_points: [],
    additional_insights: [],
    sources: []
  });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [currentPhase, setCurrentPhase] = useState(0);
  const analysisRef = useRef(null);

  // Load ICP analysis from local storage on component mount
  useEffect(() => {
    const storedData = localStorage.getItem(`icpAnalysis_${userInput}`);
    if (storedData) {
      setIcpAnalysis(JSON.parse(storedData));
      setCurrentPhase(7);
    }
  }, [userInput]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!userInput.trim() || isLoading) return;

    setIsLoading(true);
    setError(null);
    setCurrentPhase(1);

    try {
      const response = await fetch('http://127.0.0.1:5000/api/icp-analysis', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: userInput }),
      });

      if (!response.ok) {
        throw new Error('Failed to fetch data');
      }

      const data = await response.json();
      console.log('ICP API Response:', data);
      
      // Update data progressively
      if (data.demographics?.length) {
        setCurrentPhase(2);
        setIcpAnalysis(prev => ({ ...prev, demographics: data.demographics }));
      }
      if (data.psychographics?.length) {
        setCurrentPhase(3);
        setIcpAnalysis(prev => ({ ...prev, psychographics: data.psychographics }));
      }
      if (data.professional?.length) {
        setCurrentPhase(4);
        setIcpAnalysis(prev => ({ ...prev, professional: data.professional }));
      }
      if (data.pain_points?.length) {
        setCurrentPhase(5);
        setIcpAnalysis(prev => ({ ...prev, pain_points: data.pain_points }));
      }
      if (data.sources?.length) {
        setCurrentPhase(7);
        setIcpAnalysis(prev => ({ ...prev, sources: data.sources }));
      }
      
      localStorage.setItem(`icpAnalysis_${userInput}`, JSON.stringify(data));

    } catch (error) {
      console.error('Error:', error);
      setError('Failed to get ICP analysis. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text("Ideal Customer Profile Analysis", 10, 10);
    doc.setFontSize(12);
    
    const sections = [
      { title: "Demographics", data: icpAnalysis.demographics },
      { title: "Psychographics", data: icpAnalysis.psychographics },
      { title: "Professional Characteristics", data: icpAnalysis.professional },
      { title: "Pain Points & Needs", data: icpAnalysis.pain_points },
      { title: "Additional Insights", data: icpAnalysis.additional_insights },
      { title: "Data Sources", data: icpAnalysis.sources.map(source => source.domain || new URL(source.url).hostname.replace('www.', '')) }
    ];

    let yPos = 30;
    sections.forEach(section => {
      doc.setFontSize(16);
      doc.text(section.title, 10, yPos);
      yPos += 10;
      doc.setFontSize(12);
      section.data.forEach(item => {
        doc.text(`- ${item}`, 10, yPos);
        yPos += 5;
      });
      yPos += 10; // Add space between sections
    });

    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Generated by ICP Analysis Tool - Page ${i} of ${pageCount}`, 10, doc.internal.pageSize.getHeight() - 10);
    }

    doc.save("icp_analysis.pdf");
  };

  const renderIcpSection = (title, data) => {
    return (
      <div className="mb-6">
        <h3 className="text-lg font-semibold text-purple-400 mb-2">{title}</h3>
        <div className="bg-[#2D2D2F] p-4 rounded-xl">
          {data.length > 0 ? (
            <ul className="space-y-2">
              {data.map((item, index) => (
                <li key={index} className="text-gray-300">
                  {item}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-gray-400">No {title.toLowerCase()} data available.</p>
          )}
        </div>
      </div>
    );
  };

  const renderPhaseStatus = () => {
    const phases = [
      'Starting Analysis',
      'Demographics',
      'Psychographics',
      'Professional Profile',
      'Pain Points',
      'Additional Insights',
      'Data Sources'
    ];

    return (
      <div className="mb-6">
        <div className="flex items-center space-x-2">
          {phases.map((phase, index) => (
            <div key={index} className="flex items-center">
              <div className={`h-2 w-2 rounded-full ${
                currentPhase > index ? 'bg-purple-500' : 'bg-gray-600'
              }`} />
              <span className={`text-sm ml-1 ${
                currentPhase > index ? 'text-purple-400' : 'text-gray-500'
              }`}>
                {phase}
              </span>
              {index < phases.length - 1 && (
                <div className={`h-0.5 w-4 mx-2 ${
                  currentPhase > index ? 'bg-purple-500' : 'bg-gray-600'
                }`} />
              )}
            </div>
          ))}
        </div>
      </div>
    );
  };

  const renderSourcesSection = (sources) => {
    if (!sources || sources.length === 0) return null;

    return (
      <div className="mb-6">
        <h3 className="text-lg font-semibold text-purple-400 mb-2">Data Sources</h3>
        <div className="bg-[#2D2D2F] p-4 rounded-xl">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {sources.map((source, index) => (
              <div key={index} className="flex items-start space-x-3">
                <div className="flex-shrink-0 w-8 h-8 bg-purple-500/10 rounded-full flex items-center justify-center">
                  <span className="text-purple-400 text-sm">{index + 1}</span>
                </div>
                <div className="flex-grow">
                  <div className="flex justify-between items-start">
                    <a 
                      href={source.url} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-purple-400 hover:text-purple-300 transition-colors"
                    >
                      {source.domain || new URL(source.url).hostname.replace('www.', '')}
                    </a>
                    <span className="text-xs text-gray-500 ml-2">
                      {source.section || 'ICP Analysis'}
                    </span>
                  </div>
                  <p className="text-gray-400 text-sm mt-1">
                    Accessed: {source.date || new Date().toLocaleDateString()}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="text-sm text-gray-400 mt-2">
          * Data compiled from {sources.length} trusted sources
        </div>
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-[#131314] text-white p-4 sm:p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header with Navigation */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 sm:mb-8 space-y-4 sm:space-y-0">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold bg-gradient-to-r from-purple-400 via-purple-600 to-indigo-600 bg-clip-text text-transparent">
              Ideal Customer Profile Creation
            </h1>
            <p className="text-gray-400 mt-2">Define and analyze your ideal customer</p>
          </div>
          <div className="flex items-center space-x-4">
            {/* Navigation Button */}
            <Link
              href="/journey-mapping"
              className="px-4 py-2 rounded-xl font-medium bg-[#2D2D2F] text-gray-400 hover:text-white hover:bg-purple-600/50 transition-all duration-200"
            >
              Journey Mapping
            </Link>
            {icpAnalysis && (
              <button
                onClick={exportToPDF}
                className="bg-[#1D1D1F] hover:bg-[#2D2D2F] text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-all text-sm sm:text-base"
              >
                <span>📥</span>
                <span>Export PDF</span>
              </button>
            )}
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="bg-[#1D1D1F] p-1 rounded-xl mb-6 sm:mb-8 inline-flex">
          <button 
            className="px-4 py-2 rounded-lg bg-purple-600 text-white"
          >
            ICP Creation
          </button>
          <Link 
            href="/journey-mapping"
            className="px-4 py-2 rounded-lg text-gray-400 hover:text-white hover:bg-purple-600/50 transition-all duration-200"
          >
            Journey Mapping
          </Link>
        </div>

        {/* Add phase status indicator */}
        {isLoading && renderPhaseStatus()}

        {/* Main Content */}
        <div className="bg-[#1D1D1F] rounded-2xl border border-purple-500/10 p-4 sm:p-6">
          <h2 className="text-xl sm:text-2xl font-semibold mb-4 sm:mb-6 text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-purple-600">
            ICP Analysis
          </h2>
          <form onSubmit={handleSubmit} className="space-y-4 sm:space-y-6">
            <div>
              <textarea
                value={userInput}
                onChange={(e) => setUserInput(e.target.value)}
                placeholder="Enter your business details for ICP creation..."
                className="w-full h-32 sm:h-40 px-3 sm:px-4 py-2 sm:py-3 bg-[#131314] text-gray-200 rounded-xl border border-purple-500/20 
                         placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500/50 resize-none text-sm sm:text-base"
                disabled={isLoading}
              />
            </div>
            <button
              type="submit"
              disabled={isLoading || !userInput.trim()}
              className={`w-full py-3 sm:py-4 px-4 sm:px-6 rounded-xl font-medium transition-all duration-200 text-sm sm:text-base
                        ${!isLoading && userInput.trim()
                  ? 'bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white shadow-lg shadow-purple-500/25'
                  : 'bg-gray-600 text-gray-300 cursor-not-allowed'}`}
            >
              {isLoading ? (
                <div className="flex items-center justify-center space-x-2">
                  <div className="w-4 sm:w-5 h-4 sm:h-5 border-t-2 border-b-2 border-white rounded-full animate-spin"></div>
                  <span>Analyzing...</span>
                </div>
              ) : (
                'Create ICP'
              )}
            </button>
          </form>

          {/* Analysis Results */}
          <div ref={analysisRef} className="mt-6">
            {error ? (
              <div className="text-red-500">{error}</div>
            ) : (
              <div className="space-y-6">
                {renderIcpSection("Demographics", icpAnalysis.demographics)}
                {renderIcpSection("Psychographics", icpAnalysis.psychographics)}
                {renderIcpSection("Professional Characteristics", icpAnalysis.professional)}
                {renderIcpSection("Pain Points & Needs", icpAnalysis.pain_points)}
                {icpAnalysis.additional_insights?.length > 0 && (
                  renderIcpSection("Additional Insights", icpAnalysis.additional_insights)
                )}
                
                {/* Add Sources Section */}
                {renderSourcesSection(icpAnalysis.sources)}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
} 